name: MLOps with CML

on: [push, pull_request]

jobs:
  train-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Configure Git
        run: |
          git config --global user.email "202113370@alu.comillas.edu"
          git config --global user.name "sergihrs"

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Restore DVC Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/dvc
          key: dvc-cache-${{ hashFiles('dvc.yaml', 'dvc.lock') }}
          restore-keys: |
            dvc-cache-

      - name: DVC Pull
        env:
          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        run: |
          dvc remote modify origin --local user ${DAGSHUB_USERNAME}
          dvc remote modify origin --local password ${DAGSHUB_API_KEY}
          dvc pull -r origin

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml
          pip install -r requirements.txt

      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install CML manually
        run: |
          npm install -g @dvcorg/cml

      - name: Run training script
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_API_KEY }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          dvc repro

  deploy-to-gke:
    needs: train-and-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: DVC setup
        uses: iterative/setup-dvc@v1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
      - name: Set up gcloud CLI and kubectl
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: "latest"
          install_components: "gke-gcloud-auth-plugin"
      - name: Get GKE credentials
        run: gcloud container clusters get-credentials ${{vars.GKE_CLUSTER }} --zone ${{ vars.GKE_ZONE }} --project ${{vars.GCP_PROJECT_ID }}

      - name: DVC Pull
        env:
          DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        run: |
          dvc remote modify origin --local user ${DAGSHUB_USERNAME}
          dvc remote modify origin --local password ${DAGSHUB_API_KEY}
          dvc pull -r origin

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID}}/mlops-api:latest .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID}}/mlops-api:latest

      - name: Deploy to GKE
        run: |
          kubectl apply -f api-deployment.yaml
          kubectl apply -f api-service.yaml

          kubectl apply -f web-deployment.yaml
          kubectl apply -f web-service.yaml

      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker

      # --- CONSTRUIR Y SUBIR IMAGEN DE LA API (mlops-api) ---
      - name: Build and Push API Docker Image
        run: |
          # 1. Construir la imagen de la API usando Dockerfile
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-api:latest .

          # 2. Subir la imagen de la API a GCR
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-api:latest

      # --- CONSTRUIR Y SUBIR IMAGEN DE LA WEB (mlops-web) ---
      - name: Build and Push Web Docker Image
        run: |
          # 1. Construir la imagen de la WEB usando Dockerfile.web
          docker build -f Dockerfile.web -t gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-web:latest .

          # 2. Subir la imagen de la WEB a GCR
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/mlops-web:latest
